### ISSUE TITLE
关于burp插件开发

### ISSUE THREAD

**Issue by miaochiahao** [bit4woo/code2sec.com#1]
其实对于java编写的插件，burp预留了调试接口，可以参考这篇文章来打断点和动态调试：https://yuankeyang.github.io/2017/07/12/IDE%E4%B8%AD%E8%B0%83%E8%AF%95BurpSuite%E6%8F%92%E4%BB%B6/

另外想请教下，有没有找到什么python插件的调试方法能够用IDE调试的，== 目前只看到一种用pdb的方式，非常的 麻烦。。

**Comment by bit4woo** [comment]
感谢指出，我有找到Java下的调试方法 https://blog.netspi.com/debugging-burp-extensions 但一直未更新文章。最新更新的方法可以调试破解的pro版本。
关于python写插件，我已弃用，没有研究，抱歉。 #2
